pipeline {
  agent any
//  environment {
//      STORE_URL  = credentials('STORE_URL')
//      STORE_TOKEN     = credentials('STORE_TOKEN')
//  }
  stages {
    stage('Code Checkout') {
      steps {
        checkout([$class: 'GitSCM', branches: [[name: '**']], extensions: [[$class: 'CloneOption', noTags: false, reference: '', shallow: true]], userRemoteConfigs: [[credentialsId: 'GitHub-PAT-Sept-2022-v1', url: 'https://github.com/okorach/tis-demos']]])
      }
    }
    stage('Run TISA') {
      steps {
        script {
          echo "Run TrustInSoft Analyzer"
          sh "make -C caesar-c clean tis_l1 tis_l2_report tis_l2_step2 report"
        }
      }
    }
  }
}